MLM: false
alpha: 0.9
batch_size: 64
beta: 0.999
bias_lr_factor: 2.0
cmt_depth: 4
dataset_name: TAG-PEDES
distributed: false
eval_period: 1
gamma: 0.1
hire: false
hire_eval_gallery_chunk: 512
hire_eval_query_chunk: 128
hire_identity_dim: 512
hire_margin: 0.1
hire_observation_dim: 512
hire_select_ratio: 0.3
hire_state_dim: 512
hire_support_size: 3
hire_tau: 0.015
hire_tse_dim: 1024
hire_v2: true
hire_v2_aux_weight: 0.1
hire_v2_mode: identity
hire_v2_select_ratio: 0.3
hire_v2_support_size: 3
hire_v2_tse_dim: 1024
id_loss_weight: 1.0
img_aug: false
img_size: !!python/tuple
- 384
- 128
irra_light: false
irra_light_hard_negative_csv: ''
irra_light_identity_loss: sdm
irra_light_mode: single_pure
irra_light_support_consistency_csv: ''
irra_light_support_relation_csv: ''
irra_light_support_size: 3
light_stat_period: 100
local_rank: 0
log_period: 100
loss_names: hire_v2_identity
lr: 1.0e-05
lr_factor: 5.0
lrscheduler: cosine
masked_token_rate: 0.8
masked_token_unchanged_rate: 0.1
milestones: !!python/tuple
- 20
- 50
mlm_loss_weight: 1.0
momentum: 0.9
name: hire_v2_identity_tagpedes_60e_seed1_82601f8
num_epoch: 60
num_instance: 4
num_workers: 8
optimizer: Adam
output_dir: /root/autodl-tmp/HIRE_v2_identity_logs/82601f8/TAG-PEDES/20260716_201333_hire_v2_identity_tagpedes_60e_seed1_82601f8
power: 0.9
pretrain_choice: ViT-B/16
resume: false
resume_ckpt_file: ''
root_dir: /root/autodl-tmp/datasets
sampler: random
seed: 1
stride_size: 16
target_lr: 0
temperature: 0.02
test_batch_size: 512
text_length: 77
training: true
val_dataset: test
vocab_size: 49408
warmup_epochs: 5
warmup_factor: 0.1
warmup_method: linear
weight_decay: 4.0e-05
weight_decay_bias: 0.0
